metadata:
  id: hello-whisper
  language: swe

import:
  text_annotation: text
  importer: sbx_whisper_import:parse

sbx_whisper_import:
  model_size: tiny
  model_verbosity: standard

xml_export:
  annotations:
    - text
    - segment.token
