metadata:
  id: aspenstrom-ogg
  language: swe

import:
  text_annotation: text
  importer: sbx_whisper_import:parse_ogg

sbx_whisper_import:
  model_size: tiny
  model_verbosity: standard

export:
  annotations:
    - text
    - <token>
